version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "22:22"

  sts:
    image: your-username/sts:latest
    container_name: sts
    restart: always
    networks:
      - gitea
    ports:
      - "3001:3000"

networks:
  gitea:
    external: false